### ISSUE TITLE
Typo + suggestion

### ISSUE THREAD

**Issue by dsifford** [wingyplus/path-hyperclick#1]
FYI: Typo [here](https://github.com/wingyplus/path-hyperclick/blob/fa4948067b852821ff43832160a276cc9ababce3/lib/main.js#L34)

Also, when the path is a directory, why not have the package search the directory for an `index.*` file and open that if it exists?

**Comment by jacobmischka** [comment]
I don't think it should automatically parse for an index file, that's pretty complex considering you don't know the extension, and considering it's not normal behavior for a text editor or any tool really besides web browsers and module bundlers, from my experience.
